### Create Orders in two steps
# @name createOrder
POST http://localhost:4004/chat/createMessage
Content-Type: application/json

{
  "message": "Test again", 
  "channel_ID": "56f72ddc-37bc-4265-be86-ce89306d1748"
}

### Create Orders in two steps
# @name createOrder
POST http://localhost:4004/chat/createMessage
Content-Type: application/json

{
  "channel_ID": "56f72ddc-37bc-4265-be86-ce89306d1748"
}